#!/bin/bash
LC_ALL=C
SOURCE="${BASH_SOURCE[0]}"
DIR="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]
do 
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

if [ ! -e ~/.polyvr ]; then
  cp -R /usr/share/polyvr ~/.polyvr
fi
cd ~/.polyvr

libs="OSGBase:OSGContribCSMSimplePlugin:OSGContribWebInterface:OSGGroup:OSGUtil:OSGCluster:OSGContribCSM:OSGDrawable:OSGImageFileIO:OSGWindowGLUT:OSGContribBackgroundLoader:OSGContribGUI:OSGDynamics:OSGState:OSGWindow:OSGContribCgFX:OSGContribPLY:OSGEffectGroups:OSGSystem:OSGWindowX:OSGContribComputeBase:OSGContribTrapezoidalShadowMaps:OSGFileIO:OSGText"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/opensg:/usr/lib/CEF:/usr/lib/virtuose:/usr/lib/1.4 && export OSG_LOAD_LIBS=$libs && polyvr-bin
