#!/bin/sh

cd OpenSG/Examples/Tutorial
mkdir build
cd build
# append line to ../CmakeLists.txt
#  add_definitions("-DBOOST_NO_CXX11_HDR_ATOMIC=1")
rm -rf ./* && cmake .. -DCMAKE_MODULE_PATH='/usr/local/share/OpenSG/cmake' -DCMAKE_PREFIX_PATH='/usr/local/share/OpenSG' -DOPENSG_LIBRARY_DIR='/usr/local/lib64'
make -j4
