#!/bin/bash

# check for root rights
if [ `whoami` != root ]; then
echo This script needs root permissions
exit 5
fi

version=1.1
root=polyvr
pvr_base="../../polyvr"

rm -rf $root
mkdir -p $root/DEBIAN


# control file
/bin/cat <<EOM >$root/DEBIAN/control
Package: $root
Source: polyvr
Version: $version-1
Section: misc
Priority: optional
Architecture: amd64
Depends: libc6, libcollada-dev, libvrpn-dev, libmicrohttpd-dev, libjsoncpp-dev, python-gtkglext1 , python-vte, libvte-dev, libboost-program-options-dev , libboost-thread-dev , libxml++2.6-dev, libbullet-dev, libgtkmm-2.4-dev, libgtkglext1-dev, libglew-dev, libsdl1.2-dev, libgtksourceview2.0-dev, libcgal-dev, libusb-dev, python-numpy, libavcodec-dev, libavformat-dev, libswscale-dev, libqrencode-dev, libudev-dev, python-dev, libcurl4-gnutls-dev, freeglut3-dev, libboost-filesystem-dev, libjpeg-dev
Installed-Size: 84300
Homepage: https://github.com/Victor-Haefner/polyvr
Maintainer: victor haefner <victor.haefner@gmail.com>
Description: A shortcut to virtual reality.
 PolyVR is a virtual reality authoring system. 
EOM


# copyright file
mkdir -p $root/usr/share/doc/$root
/bin/cat <<EOM >$root/usr/share/doc/$root/copyright
Copyright 2014 Victor Häfner <victor.haefner@gmail.com>
This package is lisenced under the GPLv3.
The license file can be found here:
/usr/share/common-licenses/GPL-3
EOM

# man page
mkdir -p $root/usr/share/man/man1
/bin/cat <<EOM >$root/usr/share/man/man1/$root.1
PolyVR is a virtual reality authoring system.
EOM
gzip --best $root/usr/share/man/man1/$root.1

# changelog file
/bin/cat <<EOM >$root/usr/share/doc/$root/changelog.Debian
$root ($version-1) trusty; urgency=low

  * Packaged PolyVR (Closes: #573859)

 -- Victor Haefner <victor.haefner@gmail.com>  Sun, 05 Oct 2014 22:03:02 +0200
EOM
gzip --best $root/usr/share/doc/$root/changelog.Debian

# libraries and header files
d_usr=$root/usr/
d_bin=$root/usr/bin
mkdir -p $d_bin

objcopy --strip-debug --strip-unneeded $pvr_base/bin/Debug/VRFramework $d_bin/polyvr
find $d_usr -type f -exec chmod 644 {} \;
chmod 755 $d_bin/*

chown -R root $root
chgrp -R root $root
dpkg-deb --build $root && lintian $root.deb
