#!/bin/bash

# check for root rights
if [ `whoami` != root ]; then
echo This script needs root permissions
exit 5
fi

version=0.8
root=libredwg-dev

rm -rf $root
mkdir -p $root/DEBIAN


# control file
/bin/cat <<EOM >$root/DEBIAN/control
Package: $root
Source: dwg
Version: $version-1
Section: libdevel
Priority: extra
Architecture: amd64
Depends:
Installed-Size: 26600
Homepage: https://github.com/LibreDWG/libredwg.git
Maintainer: victor haefner <victor.haefner@gmail.com>
Description: DWG development package
 DWG development package
EOM


# copyright file
now="$(date +'%d/%m/%Y')"
mkdir -p $root/usr/share/doc/$root
cp libredwg/COPYING $root/usr/share/doc/$root/copyright

# changelog file
/bin/cat <<EOM >$root/usr/share/doc/$root/changelog.Debian
$root ($version-1) trusty; urgency=low

  * Packaged DWG

 -- Victor Haefner <victor.haefner@gmail.com>  Sun, 05 Oct 2014 22:03:02 +0200
EOM
gzip --best $root/usr/share/doc/$root/changelog.Debian

# libraries and header files
d_usr=$root/usr/
d_lib=$root/usr/lib/DWG/
d_inc=$root/usr/include/DWG/
mkdir -p $d_lib
mkdir -p $d_inc

cp -r libredwg/include/* $d_inc/
cp libredwg/build/usr/lib/* $d_lib/
find $d_lib -name "*.so*" -exec chrpath -d {} \; # remove rpaths
find $d_lib -name "*.a" -exec objcopy --strip-debug --strip-unneeded {} {} \; # unstrip libs
find $d_usr -type f -exec chmod 644 {} \;

chown -R root $root
chgrp -R root $root
dpkg-deb --build $root && lintian $root.deb
