#!/bin/bash

# check for root rights
if [ `whoami` != root ]; then
echo This script needs root permissions
exit 5
fi

version=7.27
root=libcollada-dev

rm -rf $root
mkdir -p $root/DEBIAN


# control file
/bin/cat <<EOM >$root/DEBIAN/control
Package: $root
Source: collada
Version: $version-1
Section: libdevel
Priority: optional
Architecture: amd64
Depends: libc6
Installed-Size: 84600
Homepage: http://sourceforge.net/projects/collada-dom/
Maintainer: victor haefner <victor.haefner@gmail.com>
Description: COLLADA development package
 COLLADA is great!
EOM


# copyright file
now="$(date +'%d/%m/%Y')"
mkdir -p $root/usr/share/doc/$root
cp collada-dom/License_Folder/license_e.txt $root/usr/share/doc/$root/copyright

# changelog file
/bin/cat <<EOM >$root/usr/share/doc/$root/changelog.Debian
$root ($version-1) trusty; urgency=low

  * Packaged COLLADA (Closes: #573859)

 -- Victor Haefner <victor.haefner@gmail.com>  Sun, 05 Oct 2014 22:03:02 +0200
EOM
gzip --best $root/usr/share/doc/$root/changelog.Debian

# libraries and header files
d_usr=$root/usr/
d_lib=$root/usr/lib/
d_inc=$root/usr/include/collada/
mkdir -p $d_lib
mkdir -p $d_inc

cp -R collada-dom/dom/include/* $d_inc
cp -R collada-dom/build/dom/src/* $d_lib
find $d_lib -name "*.so*" -exec objcopy --strip-debug --strip-unneeded {} {} \;
find $d_usr -type f -exec chmod 644 {} \;

chown -R root $root
chgrp -R root $root
dpkg-deb --build $root && lintian $root.deb
